services:
  telegram-bot:
    image: registry.marceloiglesias.net.ar/telegram-bot:latest
    container_name: telegram-bot-app
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true