services:
  app:
    build:
      context: .
      target: production
    container_name: telegram-bot-app
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - '${PORT:-3000}:3000'
    restart: unless-stopped
