name: Telegram Bot CI/CD

on: 
  push:
    branches:
      - poc/maestros-csv

concurrency:
  group: deploy-${{ forgejo.ref }}
  cancel-in-progress: true

jobs:
  build:
      runs-on: docker

      steps:
        - name: Checkout
          uses: actions/checkout@v6

        - name: Install dependencies
          run: npm ci

        - name: Build
          run: npm run build

  image:
    if: ${{ forgejo.event_name == 'push' }}
    needs: build
    runs-on: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install docker
        run: |
          apt-get update
          apt-get install -y docker.io
          docker --version

      - name: Registry login
        env:
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          printf '%s' "$REGISTRY_PASSWORD" | 
            docker login "${{ secrets.REGISTRY_HOST }}" \
              --username "${{ secrets.REGISTRY_USERNAME}}" \
              --password-stdin
      - name: Build image
        run: |
          docker build \
            -t "${{ secrets.REGISTRY_HOST}}/telegram-bot:${{ forgejo.sha }}" \
            -t "${{ secrets.REGISTRY_HOST}}/telegram-bot:latest" .

      - name: Push commit image
        run: |
          docker push \
            "${{ secrets.REGISTRY_HOST }}/telegram-bot:${{ forgejo.sha }}"

      - name: Push latest
        run: |
          docker push \
            "${{ secrets.REGISTRY_HOST}}/telegram-bot:latest"

  deploy:
    if: ${{ forgejo.event_name == 'push'}}
    needs: image
    runs-on: docker

    steps:
      - name: Configure SSH keys
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          ssh-keyscan -H "${{ secrets.DEPLOY_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh \
            -i ~/.ssh/deploy_key \
            "${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}" \
            sudo /usr/local/sbin/deploy-compose-app "{{ vars.DEPLOY_APP }}"