name: Test Forgejo Runner

on: [push]

jobs:
  test:
      runs-on: docker

      steps:
        - name: Test Runner
          run: |
            echo "Forgejo Runner funcionando"
            uname -a